name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9]
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools \
            git+https://github.com/colcon/colcon-core \
            git+https://github.com/colcon/colcon-library-path \
            pytest flake8 pydocstyle
      - name: Build colcon
        run: |
          colcon build --paths ./*
      - name: Test with pytest
        run: |
          pytest
      - name: Build test package
        run: |
          source install/setup.sh
          # We need to specify the location because it is inside a package.
          colcon build --paths colcon-dub/test/dub-test-package
