name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9]
        dc: [dmd-2.094.0]
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Install dependencies
        run: |
          # colcon-output is required to collect summary
          python -m pip install --upgrade pip
          python -m pip install setuptools \
            git+https://github.com/colcon/colcon-core \
            git+https://github.com/colcon/colcon-library-path \
            git+https://github.com/colcon/colcon-ros \
            git+https://github.com/colcon/colcon-output.git \
            pytest pytest-shell flake8 pydocstyle
      - name: Build colcon
        run: |
          colcon build --paths ./*
      - name: Build test package
        run: |
          source install/setup.sh
          # We need to specify the location because it is inside a package.
          colcon build --paths colcon-dub/test/* colcon-ros-dub/test/*
      - name: Test with pytest
        run: |
          pytest
